name: Publish VSCode Extension

on:
  push:
    paths:
      - 'Redesign-Assistant/**'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

            - name: Checkout repository code
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: Install dependencies
              run: npm install
              working-directory: Redesign-Assistant

            - name: Install vsce
              run: npm install -g @vscode/vsce

            - name: Bump version
              run: npm version patch --no-git-tag-version # "major", "minor", or "patch" depending on the size of the update
              working-directory: Redesign-Assistant

            - name: Commit version bump
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add Redesign-Assistant/package.json
                git commit -m "Bump version [skip ci]" || exit 0
                git push

            - name: Package extension
              run: vsce package --allow-missing-repository
              working-directory: Redesign-Assistant

            - name: Publish extension
              run: vsce publish --allow-missing-repository
              env:
                VSCE_PAT: ${{ secrets.VSCE_PAT }}
              working-directory: Redesign-Assistant

            - run: echo "This job's status is ${{ job.status }}."